### ISSUE TITLE
[需求] 你好，我想询问一下你的文章基于stun的伪ddns

### ISSUE THREAD

**Issue by wintsa123** [xrgzs/xrsys-osc#1]
webhook里面请求头填的key，怎么样都不行
{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}

![image](https://github.com/xrgzs/xrsys-osc/assets/47288630/9d36a7f2-cd0f-4f75-925d-62cd5d88a4c6)
我已经在这里添加了key了

**Comment by xrgzs** [comment]
您好，您提问的内容与本仓库的无关，本仓库为系统自动化部署项目，您询问的问题与网络有关，与本项目八竿子打不着关系，请您到正确的地方反馈问题，谢谢！

**Comment by wintsa123** [comment]
是的，但我不知道如何联系您
